/* =====================================================================
   inspector.ts — the right-hand property editor
   ---------------------------------------------------------------------
   Responsibility: render the Inspector pane for whatever is selected —
   a single node (label/shape/fill/size/pos), multiple nodes (align,
   distribute, bulk fill, group, delete), or an edge (label/style/routing/
   reverse/delete). Wires each control back to the model + render/sync/
   history. Read-render-write against the current selection.

   Depends on nodes (align/group/delete) and selection (clearSel).
   ===================================================================== */

import type { AppContext } from '../../core/context/context';
import type { NodesApi } from '../../interaction/nodes';
import type { SelectionApi } from '../../interaction/selection';
import type { NodeKind, DiagramNode, DiagramEdge } from '../../core/types/types';
import type { StateStore } from '../../core/state/state';
import { SHAPES, KINDS, PALETTE, PALETTE_NAMES, STYLES, DEFAULTS, esc } from '../../core/config/config';
import { isAncestor } from '../../core/state/state';
import { initInspectorFrontmatter } from './inspector-frontmatter';

export interface InspectorApi {
  renderInspector: () => void;
}

/** Bag of "stable across a single-inspector session" deps, kept to one param each call. */
interface SingleInspectorArgs {
  ctx: AppContext;
  nodesApi: NodesApi;
  renderInspector: () => void;
  fmEditor: ReturnType<typeof initInspectorFrontmatter>;
}

/** shape of one bodies.json entry (ctx.bodies value type, named for readability). */
type SourceEntry = { kind: string; body: string; accepts?: string[]; returns?: string | null };

function byId(id: string): HTMLElement {
  return document.getElementById(id) as HTMLElement;
}

function setInspectorVisibility(inspEmpty: HTMLElement, inspBody: HTMLElement, hasSelection: boolean): void {
  inspEmpty.style.display = hasSelection ? 'none' : 'block';
  inspBody.style.display = hasSelection ? 'flex' : 'none';
}

/* ---------- status line ---------- */

function renderStatusPane(state: StateStore): void {
  const statusEl = document.getElementById('status');
  if (!statusEl) return;
  const nodeCount = Object.keys(state.nodes).length;
  const edgeCount = state.edges.length;
  let statusText = `${nodeCount} node${nodeCount !== 1 ? 's' : ''}`;
  statusText += ` · ${edgeCount} edge${edgeCount !== 1 ? 's' : ''}`;
  if (state.sel.size) statusText += ` · ${state.sel.size} selected`;
  statusEl.textContent = statusText;
}

/* ---------- source pane ---------- */

function hideSourceBody(sourceEmpty: HTMLElement, sourceBody: HTMLElement): void {
  sourceEmpty.style.display = 'block';
  sourceBody.style.display = 'none';
}

function noBodiesMessage(): string {
  return 'Select a node to view its source code.<br><br>Load a <code>bodies.json</code> with the '
    + '<b>Bodies</b> button (top-right) — generated by <code>extract.mjs --bodies</code> against '
    + 'your TS project. Read locally; nothing is uploaded.';
}

function noSourceMessage(id: string): string {
  return `No source found for <code>${esc(id)}</code>.<br>Ensure the node id has a `
    + `<code>%% src</code> directive in the loaded bodies.json.`;
}

function showMissingSource(sourceEmpty: HTMLElement, sourceBody: HTMLElement, ctx: AppContext, id: string): void {
  hideSourceBody(sourceEmpty, sourceBody);
  sourceEmpty.innerHTML = ctx.bodies ? noSourceMessage(id) : noBodiesMessage();
}

function buildSourceSignatureHtml(entry: SourceEntry): string {
  const accepts = entry.accepts ?? [];
  const returns = entry.returns ?? null;
  if (!accepts.length && !returns) return '';
  const params = accepts.map((arg) => `  ${esc(arg)}`).join(',\n');
  const head = accepts.length ? `(\n${params}\n)` : '()';
  const tail = returns ? ` → ${esc(returns)}` : '';
  return `<span class="src-sig">${head}${tail}</span>`;
}

function buildSourceBodyHtml(entry: SourceEntry): string {
  const sig = buildSourceSignatureHtml(entry);
  return `<span class="src-kind">${esc(entry.kind)}</span>${sig}${esc(entry.body)}`;
}

function renderSourcePane(ctx: AppContext): void {
  const sourceEmpty = document.getElementById('sourceEmpty');
  const sourceBody = document.getElementById('sourceBody');
  if (!sourceEmpty || !sourceBody) return;
  const { state } = ctx;
  if (state.sel.size !== 1) return hideSourceBody(sourceEmpty, sourceBody);
  const id = [...state.sel][0];
  const entry = ctx.bodies?.get(id);
  if (!entry) return showMissingSource(sourceEmpty, sourceBody, ctx, id);
  sourceEmpty.style.display = 'none';
  sourceBody.style.display = 'block';
  sourceBody.innerHTML = buildSourceBodyHtml(entry);
}

/* ---------- single-node inspector: markup ---------- */

function shapeOptionsHtml(node: DiagramNode): string {
  return SHAPES.map((shape) =>
    `<option value="${shape}" ${shape === node.shape ? 'selected' : ''}>${shape}</option>`).join('');
}

function kindOptionsHtml(node: DiagramNode): string {
  const none = `<option value="" ${!node.kind ? 'selected' : ''}>(none)</option>`;
  const rest = KINDS.map((kind) =>
    `<option value="${kind}" ${kind === node.kind ? 'selected' : ''}>${kind}</option>`).join('');
  return none + rest;
}

function parentOptionHtml(state: StateStore, node: DiagramNode, pid: string): string {
  const parentNode = state.nodes[pid];
  const groupSuffix = parentNode.shape === 'group' ? ' (group)' : '';
  const selected = pid === node.parent ? 'selected' : '';
  return `<option value="${pid}" ${selected}>${esc(parentNode.label)}${groupSuffix}</option>`;
}

function parentOptionsHtml(state: StateStore, node: DiagramNode): string {
  const top = `<option value="" ${!node.parent ? 'selected' : ''}>Top level</option>`;
  const rest = Object.keys(state.nodes)
    .filter((pid) => pid !== node.id && !isAncestor(state, node.id, pid))
    .map((pid) => parentOptionHtml(state, node, pid))
    .join('');
  return top + rest;
}

function swatchesHtml(selectedColor: string | null): string {
  return PALETTE.map((color, i) =>
    `<div class="sw ${color === selectedColor ? 'on' : ''}" data-c="${color}" `
    + `title="${PALETTE_NAMES[i]}" style="background:${color}"></div>`).join('');
}

function sizePosFieldsHtml(node: DiagramNode): string {
  return `
    <div class="insp-sec-title">Size & position</div>
    <div class="row2">
      <div class="field"><label>W</label><input id="iW" type="number" value="${Math.round(node.w)}"></div>
      <div class="field"><label>H</label><input id="iH" type="number" value="${Math.round(node.h)}"></div>
    </div>
    <div class="row2">
      <div class="field"><label>X</label><input id="iX" type="number" value="${Math.round(node.x)}"></div>
      <div class="field"><label>Y</label><input id="iY" type="number" value="${Math.round(node.y)}"></div>
    </div>`;
}

function buildSingleInspectorHtml(state: StateStore, node: DiagramNode): string {
  return `
    <div class="field"><label>Label</label><input id="iLabel" value="${esc(node.label)}"></div>
    <div class="field"><label>Shape</label><select id="iShape">${shapeOptionsHtml(node)}</select></div>
    <div class="field"><label>Kind</label><select id="iKind">${kindOptionsHtml(node)}</select></div>
    <div class="field"><label>Parent (drill container)</label>
      <select id="iParent">${parentOptionsHtml(state, node)}</select></div>
    <div class="field"><label>Fill</label>
      <div class="swatches" id="iSw">${swatchesHtml(node.color)}</div></div>
    ${sizePosFieldsHtml(node)}
    <div id="fmHost" class="fm-host"></div>
    <button class="filebtn danger" id="iDel">Delete node</button>`;
}

/* ---------- single-node inspector: wiring ---------- */

function wireLabelField(ctx: AppContext, node: DiagramNode): void {
  const labelInput = byId('iLabel') as HTMLInputElement;
  labelInput.oninput = (e) => {
    node.label = (e.target as HTMLInputElement).value;
    ctx.hooks.render();
    ctx.hooks.sync();
  };
  labelInput.onchange = () => ctx.hooks.pushHistory();
}

function wireShapeField(ctx: AppContext, node: DiagramNode, renderInspector: () => void): void {
  const shapeSelect = byId('iShape') as HTMLSelectElement;
  shapeSelect.onchange = (e) => {
    node.shape = (e.target as HTMLSelectElement).value as typeof node.shape;
    void DEFAULTS[node.shape];
    ctx.hooks.render();
    ctx.hooks.sync();
    renderInspector();
    ctx.hooks.pushHistory();
  };
}

function wireKindField(nodesApi: NodesApi, node: DiagramNode): void {
  const kindSelect = byId('iKind') as HTMLSelectElement;
  kindSelect.onchange = (e) => {
    const value = (e.target as HTMLSelectElement).value;
    nodesApi.setNodeMeta(node.id, { kind: value ? (value as NodeKind) : null });
  };
}

function wireParentField(ctx: AppContext, node: DiagramNode, renderInspector: () => void): void {
  const parentSelect = byId('iParent') as HTMLSelectElement;
  parentSelect.onchange = (e) => {
    const value = (e.target as HTMLSelectElement).value;
    node.parent = value || null;
    ctx.hooks.render();
    ctx.hooks.sync();
    renderInspector();
    ctx.hooks.pushHistory();
  };
}

function wireSwatches(ctx: AppContext, node: DiagramNode, renderInspector: () => void): void {
  byId('iSw').querySelectorAll('.sw').forEach((swatchRaw) => {
    const swatch = swatchRaw as HTMLElement;
    swatch.onclick = () => {
      node.color = swatch.dataset.c === 'null' ? null : (swatch.dataset.c as string);
      ctx.hooks.render();
      ctx.hooks.sync();
      renderInspector();
      ctx.hooks.pushHistory();
    };
  });
}

function applySizePosField(node: DiagramNode, field: 'W' | 'H' | 'X' | 'Y', value: number): void {
  if (field === 'W') node['w'] = Math.max(40, value);
  if (field === 'H') node['h'] = Math.max(30, value);
  if (field === 'X') node.x = value;
  if (field === 'Y') node.y = value;
}

function wireSizePosFields(ctx: AppContext, node: DiagramNode): void {
  (['W', 'H', 'X', 'Y'] as const).forEach((field) => {
    const input = byId('i' + field) as HTMLInputElement;
    input.oninput = () => {
      applySizePosField(node, field, +input.value || 0);
      ctx.hooks.render();
      ctx.hooks.sync();
    };
    input.onchange = () => ctx.hooks.pushHistory();
  });
}

function wireDeleteButton(nodesApi: NodesApi): void {
  (byId('iDel') as HTMLButtonElement).onclick = () => nodesApi.deleteSelection();
}

function wireSingleInspector(args: SingleInspectorArgs, node: DiagramNode): void {
  wireLabelField(args.ctx, node);
  wireShapeField(args.ctx, node, args.renderInspector);
  wireKindField(args.nodesApi, node);
  wireParentField(args.ctx, node, args.renderInspector);
  wireSwatches(args.ctx, node, args.renderInspector);
  wireSizePosFields(args.ctx, node);
  wireDeleteButton(args.nodesApi);
  args.fmEditor.renderFrontmatterSection(byId('fmHost'), node);
}

function runSingleInspector(args: SingleInspectorArgs, body: HTMLElement): void {
  const node = args.ctx.state.nodes[[...args.ctx.state.sel][0]];
  body.innerHTML = buildSingleInspectorHtml(args.ctx.state, node);
  wireSingleInspector(args, node);
}

/* ---------- multi-node inspector ---------- */

function multiSwatchesHtml(): string {
  return PALETTE.map((color, i) =>
    `<div class="sw" data-c="${color}" title="${PALETTE_NAMES[i]}" style="background:${color}"></div>`).join('');
}

function alignDistributeHtml(): string {
  return `
    <div class="insp-sec-title">Align</div>
    <div class="align-grid">
      <button class="filebtn" data-al="left"   title="Align left">⬅</button>
      <button class="filebtn" data-al="cx"     title="Center horizontally">↔</button>
      <button class="filebtn" data-al="right"  title="Align right">➡</button>
      <button class="filebtn" data-al="top"    title="Align top">⬆</button>
      <button class="filebtn" data-al="cy"     title="Center vertically">↕</button>
      <button class="filebtn" data-al="bottom" title="Align bottom">⬇</button>
    </div>
    <div class="insp-sec-title">Distribute</div>
    <div class="row2">
      <button class="filebtn" data-al="dh">Horizontal</button>
      <button class="filebtn" data-al="dv">Vertical</button>
    </div>`;
}

function buildMultiInspectorHtml(state: StateStore): string {
  return `
    <div class="multi-note">${state.sel.size} nodes selected</div>
    ${alignDistributeHtml()}
    <div class="insp-sec-title">Fill</div>
    <div class="field"><div class="swatches" id="mSw">${multiSwatchesHtml()}</div></div>
    <button class="filebtn" id="mGroup">Wrap in group</button>
    <button class="filebtn danger" id="mDel">Delete ${state.sel.size} nodes</button>`;
}

function wireAlignButtons(ctx: AppContext, nodesApi: NodesApi, body: HTMLElement): void {
  body.querySelectorAll('[data-al]').forEach((btnRaw) => {
    const btn = btnRaw as HTMLElement;
    btn.onclick = () => {
      nodesApi.alignNodes(btn.dataset.al as string);
      ctx.hooks.pushHistory();
    };
  });
}

function wireMultiSwatches(ctx: AppContext, state: StateStore): void {
  byId('mSw').querySelectorAll('.sw').forEach((swatchRaw) => {
    const swatch = swatchRaw as HTMLElement;
    swatch.onclick = () => {
      const color = swatch.dataset.c === 'null' ? null : (swatch.dataset.c as string);
      state.sel.forEach((id) => {
        if (state.nodes[id].shape !== 'group' && state.nodes[id].shape !== 'note') state.nodes[id].color = color;
      });
      ctx.hooks.render();
      ctx.hooks.sync();
      ctx.hooks.pushHistory();
    };
  });
}

function wireGroupButton(nodesApi: NodesApi): void {
  (byId('mGroup') as HTMLButtonElement).onclick = () => nodesApi.wrapInGroup();
}

function wireMultiDeleteButton(nodesApi: NodesApi): void {
  (byId('mDel') as HTMLButtonElement).onclick = () => nodesApi.deleteSelection();
}

function wireMultiInspector(ctx: AppContext, nodesApi: NodesApi, body: HTMLElement): void {
  wireAlignButtons(ctx, nodesApi, body);
  wireMultiSwatches(ctx, ctx.state);
  wireGroupButton(nodesApi);
  wireMultiDeleteButton(nodesApi);
}

function runMultiInspector(ctx: AppContext, nodesApi: NodesApi, body: HTMLElement): void {
  body.innerHTML = buildMultiInspectorHtml(ctx.state);
  wireMultiInspector(ctx, nodesApi, body);
}

/* ---------- edge inspector ---------- */

function edgeStyleOptionsHtml(edge: DiagramEdge): string {
  return Object.keys(STYLES).map((styleName) =>
    `<option ${styleName === edge.style ? 'selected' : ''}>${styleName}</option>`).join('');
}

function buildEdgeInspectorHtml(
  edge: DiagramEdge, fromNode: DiagramNode | undefined, toNode: DiagramNode | undefined,
): string {
  return `
    <div class="multi-note" style="font-size:11.5px; color:var(--ink-dim)">
      ${esc(fromNode?.label || '?')} → ${esc(toNode?.label || '?')}</div>
    <div class="field"><label>Edge label</label>
      <input id="eLabel" value="${esc(edge.label || '')}" placeholder="writes / reads / fires"></div>
    <div class="field"><label>Line style</label><select id="eStyle">${edgeStyleOptionsHtml(edge)}</select></div>
    <div class="field"><label>Routing</label><select id="eRoute">
      <option value="straight" ${edge.routing !== 'ortho' ? 'selected' : ''}>straight</option>
      <option value="ortho" ${edge.routing === 'ortho' ? 'selected' : ''}>orthogonal</option>
    </select></div>
    <button class="filebtn" id="eReset">Reset route &amp; label</button>
    <button class="filebtn" id="eFlip">Reverse direction</button>
    <button class="filebtn danger" id="eDel">Delete edge</button>`;
}

function wireEdgeLabelField(ctx: AppContext, nodesApi: NodesApi, edge: DiagramEdge): void {
  const labelInput = byId('eLabel') as HTMLInputElement;
  labelInput.oninput = (e) => nodesApi.setEdgeLabel(edge.id, (e.target as HTMLInputElement).value);
  labelInput.onchange = () => ctx.hooks.pushHistory();
}

function wireEdgeStyleField(ctx: AppContext, edge: DiagramEdge): void {
  const styleSelect = byId('eStyle') as HTMLSelectElement;
  styleSelect.onchange = (e) => {
    edge.style = (e.target as HTMLSelectElement).value as typeof edge.style;
    ctx.hooks.render();
    ctx.hooks.sync();
    ctx.hooks.pushHistory();
  };
}

function wireEdgeRouteField(ctx: AppContext, edge: DiagramEdge): void {
  const routeSelect = byId('eRoute') as HTMLSelectElement;
  routeSelect.onchange = (e) => {
    edge.routing = (e.target as HTMLSelectElement).value as typeof edge.routing;
    ctx.hooks.render();
    ctx.hooks.sync();
    ctx.hooks.pushHistory();
  };
}

function wireEdgeResetButton(ctx: AppContext, edge: DiagramEdge): void {
  (byId('eReset') as HTMLButtonElement).onclick = () => {
    edge.bend = null;
    edge.labelPos = null;
    ctx.hooks.render();
    ctx.hooks.sync();
    ctx.hooks.reroute();
    ctx.hooks.pushHistory();
  };
}

function wireEdgeFlipButton(nodesApi: NodesApi, edge: DiagramEdge): void {
  (byId('eFlip') as HTMLButtonElement).onclick = () => nodesApi.reverseEdge(edge.id);
}

function wireEdgeDeleteButton(nodesApi: NodesApi, edge: DiagramEdge): void {
  (byId('eDel') as HTMLButtonElement).onclick = () => nodesApi.deleteEdge(edge.id);
}

function wireEdgeInspector(ctx: AppContext, nodesApi: NodesApi, edge: DiagramEdge): void {
  wireEdgeLabelField(ctx, nodesApi, edge);
  wireEdgeStyleField(ctx, edge);
  wireEdgeRouteField(ctx, edge);
  wireEdgeResetButton(ctx, edge);
  wireEdgeFlipButton(nodesApi, edge);
  wireEdgeDeleteButton(nodesApi, edge);
}

function runEdgeInspector(ctx: AppContext, nodesApi: NodesApi, selectionApi: SelectionApi, body: HTMLElement): void {
  const edge = ctx.state.edges.find((candidate) => candidate.id === ctx.state.selEdge);
  if (!edge) return selectionApi.clearSel();
  body.innerHTML = buildEdgeInspectorHtml(edge, ctx.state.nodes[edge.from], ctx.state.nodes[edge.to]);
  wireEdgeInspector(ctx, nodesApi, edge);
}

type InspectorRenderers = {
  edge: (body: HTMLElement) => void; multi: (body: HTMLElement) => void; single: (body: HTMLElement) => void;
};

/** which body-render call to make, keyed by selection shape — kept as one module-scope
    call so renderInspector's own dispatch collapses to a single statement. */
function dispatchInspectorRender(ctx: AppContext, renderers: InspectorRenderers, body: HTMLElement): void {
  if (ctx.state.selEdge) renderers.edge(body);
  else if (ctx.state.sel.size > 1) renderers.multi(body);
  else if (ctx.state.sel.size > 0) renderers.single(body);
}

/* ---------- init ---------- */

export function initInspector(ctx: AppContext, nodes: NodesApi, selection: SelectionApi): InspectorApi {
  const inspEmpty = byId('inspEmpty'), inspBody = byId('inspBody'), fmEditor = initInspectorFrontmatter(ctx);

  function renderInspector(): void {
    setInspectorVisibility(inspEmpty, inspBody, ctx.state.sel.size > 0 || !!ctx.state.selEdge);
    dispatchInspectorRender(
      ctx, { edge: renderEdgeInspector, multi: renderMultiInspector, single: renderSingleInspector }, inspBody);
    updateStatus();
    updateSource(); }

  function updateSource(): void {
    renderSourcePane(ctx); }

  function updateStatus(): void {
    renderStatusPane(ctx.state); }

  function renderSingleInspector(body: HTMLElement): void {
    runSingleInspector({ ctx, nodesApi: nodes, renderInspector, fmEditor }, body); }

  function renderMultiInspector(body: HTMLElement): void {
    runMultiInspector(ctx, nodes, body); }
  function renderEdgeInspector(body: HTMLElement): void {
    runEdgeInspector(ctx, nodes, selection, body); }

  return { renderInspector };
}
